# Generated by Django 5.2 on 2025-05-08 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_crear_grupos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarioincidencia',
            name='autor',
        ),
    ]
