# Generated by Django 5.2 on 2025-05-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0005_remove_mensaje_titulo_mensaje_incidencia_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensaje',
            new_name='Notificacion',
        ),
    ]
